// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Thesis.Models;

public partial class ConsultationInventory
{
    public int ConsultationInventoryId { get; set; }

    public int ConsultationId { get; set; }

    public int BatchId { get; set; }

    public int QuantityUsed { get; set; }

    public string Notes { get; set; }

    public virtual InventoryBatch Batch { get; set; }

    public virtual Consultation Consultation { get; set; }
}