// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Thesis.Models;

public partial class Consultation
{
    public int ConsultationId { get; set; }

    public int PatientId { get; set; }

    public int DoctorId { get; set; }

    public int? AppointmentId { get; set; }

    public DateTime ConsultationDate { get; set; }

    public string Notes { get; set; }

    public string Diagnosis { get; set; }

    public string Treatment { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual ICollection<ConsultationInventory> ConsultationInventories { get; set; } = new List<ConsultationInventory>();

    public virtual Doctor Doctor { get; set; }

    public virtual ICollection<LabOrder> LabOrders { get; set; } = new List<LabOrder>();

    public virtual Patient Patient { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<QueueEntry> QueueEntries { get; set; } = new List<QueueEntry>();
}