// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Thesis.Models;

public partial class InventoryItem
{
    public int ItemId { get; set; }

    public string ItemName { get; set; }

    public string ItemCategory { get; set; }

    public string ItemDescription { get; set; }

    public string Unit { get; set; }

    public int ReorderLevel { get; set; }

    public int? SupplierId { get; set; }

    public DateOnly DateAdded { get; set; }

    public virtual ICollection<InventoryBatch> InventoryBatches { get; set; } = new List<InventoryBatch>();

    public virtual Supplier Supplier { get; set; }
}