// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Thesis.Models;

public partial class InventoryBatch
{
    public int BatchId { get; set; }

    public int ItemId { get; set; }

    public string BatchNumber { get; set; }

    public int QuantityInStock { get; set; }

    public DateOnly ExpirationDate { get; set; }

    public DateOnly DateReceived { get; set; }

    public virtual ICollection<ConsultationInventory> ConsultationInventories { get; set; } = new List<ConsultationInventory>();

    public virtual ICollection<InventoryTransaction> InventoryTransactions { get; set; } = new List<InventoryTransaction>();

    public virtual InventoryItem Item { get; set; }
}