// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Thesis.Models;

public partial class InventoryTransaction
{
    public int TransactionId { get; set; }

    public int BatchId { get; set; }

    public int QuantityChange { get; set; }

    public string TransactionType { get; set; }

    public int? ReferenceId { get; set; }

    public int? PerformedByUserId { get; set; }

    public DateTime TransactionDate { get; set; }

    public virtual InventoryBatch Batch { get; set; }

    public virtual User PerformedByUser { get; set; }
}