// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Thesis.Models;

public partial class LabOrder
{
    public int LabOrderId { get; set; }

    public int ConsultationId { get; set; }

    public int PatientId { get; set; }

    public int OrderedByUserId { get; set; }

    public DateOnly OrderDate { get; set; }

    public string Notes { get; set; }

    public virtual Consultation Consultation { get; set; }

    public virtual ICollection<LabResult> LabResults { get; set; } = new List<LabResult>();

    public virtual User OrderedByUser { get; set; }

    public virtual Patient Patient { get; set; }
}