// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Thesis.Models;

public partial class LabResult
{
    public int LabResultId { get; set; }

    public int LabOrderId { get; set; }

    public string TestName { get; set; }

    public string ResultValue { get; set; }

    public string Unit { get; set; }

    public string ReferenceRange { get; set; }

    public DateOnly? DateReported { get; set; }

    public string Notes { get; set; }

    public virtual LabOrder LabOrder { get; set; }
}