// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Thesis.Models;

public partial class Patient
{
    public int PatientId { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string ContactNo { get; set; }

    public string Email { get; set; }

    public DateOnly BirthDate { get; set; }

    public string PatientSex { get; set; }

    public virtual ICollection<Appointment> Appointments { get; set; } = new List<Appointment>();

    public virtual ICollection<Consultation> Consultations { get; set; } = new List<Consultation>();

    public virtual ICollection<LabOrder> LabOrders { get; set; } = new List<LabOrder>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<QueueEntry> QueueEntries { get; set; } = new List<QueueEntry>();
}