// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Thesis.Models;

public partial class Payment
{
    public int PaymentId { get; set; }

    public int PatientId { get; set; }

    public int ConsultationId { get; set; }

    public int? AppointmentId { get; set; }

    public decimal Amount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentReason { get; set; }

    public DateTime? PaymentDate { get; set; }

    public int RecordedByUserId { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual Consultation Consultation { get; set; }

    public virtual Patient Patient { get; set; }

    public virtual User RecordedByUser { get; set; }
}