// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Thesis.Models;

public partial class QueueEntry
{
    public int QueueEntryId { get; set; }

    public int PatientId { get; set; }

    public int? AppointmentId { get; set; }

    public DateTime CreatedAt { get; set; }

    public string Status { get; set; }

    public int? DoctorId { get; set; }

    public int? ConsultationId { get; set; }

    public virtual Appointment Appointment { get; set; }

    public virtual Consultation Consultation { get; set; }

    public virtual Doctor Doctor { get; set; }

    public virtual Patient Patient { get; set; }
}