// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Thesis.Models;

public partial class User
{
    public int UserId { get; set; }

    public string Username { get; set; }

    public string UserPassword { get; set; }

    public string Email { get; set; }

    public string ContactNo { get; set; }

    public int RoleId { get; set; }

    public bool IsActive { get; set; }

    public virtual ICollection<Doctor> Doctors { get; set; } = new List<Doctor>();

    public virtual ICollection<InventoryTransaction> InventoryTransactions { get; set; } = new List<InventoryTransaction>();

    public virtual ICollection<LabOrder> LabOrders { get; set; } = new List<LabOrder>();

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual Role Role { get; set; }

    public virtual ICollection<Staff> Staff { get; set; } = new List<Staff>();
}